# Generated by Django 4.0.3 on 2024-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_menu_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
