# Generated by Django 4.0.3 on 2024-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('일식', '일식'), ('분식', '분식'), ('기타', '기타'), ('양식', '양식')], max_length=50),
        ),
    ]
