# Generated by Django 4.0.6 on 2024-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_menu_location_menu_menu_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('충정로', '충정로'), ('아현동', '아현동'), ('풍산빌딩 지하', '풍산빌딩 지하'), ('서대문', '서대문')], max_length=50),
        ),
    ]
