# Generated by Django 4.0.6 on 2024-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_alter_menu_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('진행중', '진행중'), ('완료', '완료')], default='대기중', max_length=10)),
            ],
        ),
    ]
